<?php

return [
    'kpis' => [
        ['title' => 'Total Users', 'value' => '1,284'],
        ['title' => 'Active Workflows', 'value' => '42'],
        ['title' => 'Pending Tasks', 'value' => '96'],
        ['title' => 'Overdue Tasks', 'value' => '14'],
    ],
    'weekly_tasks' => [
        ['label' => 'Mon', 'value' => 8],
        ['label' => 'Tue', 'value' => 11],
        ['label' => 'Wed', 'value' => 9],
        ['label' => 'Thu', 'value' => 13],
        ['label' => 'Fri', 'value' => 15],
        ['label' => 'Sat', 'value' => 6],
        ['label' => 'Sun', 'value' => 4],
    ],
    'workflow_progress' => [
        ['label' => 'Move-Out', 'value' => 72],
        ['label' => 'Move-In', 'value' => 64],
        ['label' => 'Inspection', 'value' => 51],
        ['label' => 'Maintenance', 'value' => 83],
    ],
    'activity' => [
        ['title' => 'Workflow completed', 'subtitle' => 'Lease renewal flow for Tower B, Unit 401', 'time' => '2 mins ago'],
        ['title' => 'New user invited', 'subtitle' => 'Priya Shah added as Property Manager', 'time' => '25 mins ago'],
        ['title' => 'Template updated', 'subtitle' => 'Periodic Inspection checklist revised', 'time' => '1 hour ago'],
        ['title' => 'Task overdue alert', 'subtitle' => 'Move-Out: Final utility closure pending', 'time' => '2 hours ago'],
    ],
    'users' => [
        ['name' => 'Karan Jain', 'email' => 'karan@todoistadmin.com', 'role' => 'superadmin', 'status' => 'Active'],
        ['name' => 'Priya Shah', 'email' => 'priya@todoistadmin.com', 'role' => 'admin', 'status' => 'Active'],
        ['name' => 'Aman Kapoor', 'email' => 'aman@todoistadmin.com', 'role' => 'manager', 'status' => 'Inactive'],
        ['name' => 'Sara Wilson', 'email' => 'sara@todoistadmin.com', 'role' => 'member', 'status' => 'Active'],
    ],
    'projects' => [
        ['id' => 'proj-1', 'name' => 'Green Heights Estate', 'code' => 'GH', 'category' => 'Residential', 'description' => 'Primary residential tower portfolio.'],
        ['id' => 'proj-2', 'name' => 'Metro Business Park', 'code' => 'MBP', 'category' => 'Commercial', 'description' => 'Office and retail mixed-use campus.'],
        ['id' => 'proj-3', 'name' => 'Riverside Warehousing', 'code' => 'RW', 'category' => 'Industrial', 'description' => 'Logistics and storage facilities.'],
    ],
    'task_categories' => [
        ['id' => 'tc-1', 'name' => 'Operations'],
        ['id' => 'tc-2', 'name' => 'Leasing'],
        ['id' => 'tc-3', 'name' => 'Finance'],
        ['id' => 'tc-4', 'name' => 'Maintenance'],
        ['id' => 'tc-5', 'name' => 'Compliance'],
    ],
    'workflows' => [
        [
            'id' => 'wf-1',
            'name' => 'Move-Out Workflow - Unit 14B',
            'status' => 'In Progress',
            'progress' => 68,
            'deadline' => 'Apr 13, 2026',
            'project_id' => 'proj-1',
            'category' => 'Operations',
            'assigned' => ['Priya Shah', 'Aman Kapoor'],
            'tasks' => ['Inspection', 'Meter Reading', 'Deposit Settlement'],
        ],
        [
            'id' => 'wf-2',
            'name' => 'Lease Onboarding - Green Heights',
            'status' => 'On Track',
            'progress' => 83,
            'deadline' => 'Apr 9, 2026',
            'project_id' => 'proj-1',
            'category' => 'Leasing',
            'assigned' => ['Sara Wilson'],
            'tasks' => ['Document KYC', 'Contract Sign', 'Welcome Kit'],
        ],
        [
            'id' => 'wf-3',
            'name' => 'Maintenance Request - Block C',
            'status' => 'Blocked',
            'progress' => 34,
            'deadline' => 'Apr 11, 2026',
            'project_id' => 'proj-2',
            'category' => 'Maintenance',
            'assigned' => ['Aman Kapoor', 'Rohit Verma'],
            'tasks' => ['Vendor Assignment', 'Repair', 'Quality Check'],
        ],
    ],
    'templates' => [
        ['id' => 'tpl-1', 'name' => 'Move-Out Workflow', 'category' => 'Tenancy', 'description' => 'Checklist for smooth tenant move-out and closure.', 'steps' => ['Notice confirmation', 'Inspection', 'Settlement', 'Handover']],
        ['id' => 'tpl-2', 'name' => 'Move-In Workflow', 'category' => 'Tenancy', 'description' => 'Structured move-in flow for new tenants.', 'steps' => ['Agreement sign', 'Access setup', 'Orientation', 'Welcome note']],
        ['id' => 'tpl-3', 'name' => 'Periodic Inspection', 'category' => 'Operations', 'description' => 'Routine inspection checklist for units and common areas.', 'steps' => ['Schedule visit', 'Safety checks', 'Notes', 'Report generation']],
        ['id' => 'tpl-4', 'name' => 'Maintenance Request', 'category' => 'Operations', 'description' => 'Process template for resident maintenance requests.', 'steps' => ['Ticket intake', 'Assign vendor', 'Resolve issue', 'Confirm closure']],
        ['id' => 'tpl-5', 'name' => 'Lease Onboarding', 'category' => 'Leasing', 'description' => 'Onboarding flow for new lease activation.', 'steps' => ['KYC', 'Payment setup', 'Move-in prep', 'Tenant kickoff']],
        ['id' => 'tpl-6', 'name' => 'Lease Renewal', 'category' => 'Leasing', 'description' => 'Renewal sequence with reminders and approvals.', 'steps' => ['Renewal reminder', 'Negotiation', 'Contract update', 'Sign-off']],
        ['id' => 'tpl-7', 'name' => 'Rent Arrears Follow-Up', 'category' => 'Finance', 'description' => 'Follow-up cadence for overdue rent collections.', 'steps' => ['Soft reminder', 'Call follow-up', 'Escalation', 'Resolution log']],
        ['id' => 'tpl-8', 'name' => 'Owner Update Checklist', 'category' => 'Stakeholder', 'description' => 'Periodic status updates for property owners.', 'steps' => ['Performance summary', 'Open issues', 'Financial note', 'Next actions']],
    ],
    'tasks' => [
        ['id' => 'task-1', 'title' => 'Finalize move-out inspection', 'due_date' => 'Apr 7, 2026', 'priority' => 'High', 'status' => 'Pending', 'assigned_user' => 'Priya Shah', 'project_id' => 'proj-1', 'workflow_id' => 'wf-1', 'category' => 'Operations', 'team' => 'Field Ops', 'notes' => 'Tenant requested evening slot for final walkthrough.'],
        ['id' => 'task-2', 'title' => 'Upload lease renewal draft', 'due_date' => 'Apr 8, 2026', 'priority' => 'Medium', 'status' => 'In Progress', 'assigned_user' => 'Karan Jain', 'project_id' => 'proj-1', 'workflow_id' => 'wf-2', 'category' => 'Leasing', 'team' => 'Leasing Desk', 'notes' => 'Add updated parking clause before review.'],
        ['id' => 'task-3', 'title' => 'Vendor follow-up for HVAC repair', 'due_date' => 'Apr 6, 2026', 'priority' => 'High', 'status' => 'Overdue', 'assigned_user' => 'Aman Kapoor', 'project_id' => 'proj-2', 'workflow_id' => 'wf-3', 'category' => 'Maintenance', 'team' => 'Vendor Mgmt', 'notes' => 'Escalate if no response by noon.'],
        ['id' => 'task-4', 'title' => 'Send owner monthly summary', 'due_date' => 'Apr 10, 2026', 'priority' => 'Low', 'status' => 'Done', 'assigned_user' => 'Sara Wilson', 'project_id' => 'proj-1', 'workflow_id' => '', 'category' => 'Finance', 'team' => 'Owner Relations', 'notes' => 'Attach occupancy trend chart snapshot.'],
    ],
    'notifications' => [
        ['id' => 'n-1', 'title' => 'Task update', 'type' => 'Task', 'message' => 'Finalize move-out inspection was marked In Progress.', 'time' => '5 mins ago'],
        ['id' => 'n-2', 'title' => 'Workflow update', 'type' => 'Workflow', 'message' => 'Lease Onboarding reached 83% completion.', 'time' => '40 mins ago'],
        ['id' => 'n-3', 'title' => 'System alert', 'type' => 'System', 'message' => 'Reminder queue reached 90% daily threshold.', 'time' => '2 hours ago'],
    ],
    'daily_activity' => [
        ['label' => 'Mon', 'value' => 24],
        ['label' => 'Tue', 'value' => 29],
        ['label' => 'Wed', 'value' => 18],
        ['label' => 'Thu', 'value' => 31],
        ['label' => 'Fri', 'value' => 26],
    ],
    'monthly_summary' => [
        ['label' => 'Jan', 'value' => 72],
        ['label' => 'Feb', 'value' => 68],
        ['label' => 'Mar', 'value' => 80],
        ['label' => 'Apr', 'value' => 76],
    ],
    'settings' => [
        'organization_name' => 'Taskerer',
        'timezone' => 'Asia/Kolkata',
        'email_notifications' => true,
        'push_notifications' => true,
        'twilio_sid' => '',
        'twilio_token' => '',
        'twilio_from' => '',
    ],
];
